name: Publish to ghcr.io

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
        -  src/**

jobs:
  publish-psql-db-migrate-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the psql-db-migrate Docker image
      run: |
        docker build . --tag ghcr.io/subsbase/psql-db-migrate:latest
        docker run ghcr.io/subsbase/psql-db-migrate:latest
        docker push ghcr.io/subsbase/psql-db-migrate:latest
